# 新增



```python
## models.py
from tortoise import Model, fields


class Proverbs(Model):
    id = fields.IntField(pk=True, description='ID', )
    proverb = fields.CharField(unique=True, max_length=200, description='谚语', )
    author = fields.CharField(max_length=100, description='作者', )
    description = fields.CharField(max_length=1000, null=True, description='描述', )

```



```python
## main.py
## 模型与初始化

from tortoise import Tortoise, run_async
from models import Proverbs

TORTOISE_ORM = {
    "connections": {
        "default": "mysql://peewee:Guoximing123@10.10.10.200:3306/peewee",
    },
    "apps": {
        "models": {"models": ["models", 'aerich.models'], "default_connection": "default"},
    },
}


# 初始化数据库连接函数
async def init_db():
    await Tortoise.init(config=TORTOISE_ORM)
    await Tortoise.generate_schemas()


# 关闭数据库连接函数
# run_async 是会自动关闭连接的，如果在其他地方或框架使用，则需要自主关闭
async def close_db():
    await Tortoise.close_connections()


run_async(init_db())
```



## 单个数据新增

### create

成功返回数据对象，通过 `.` 获取数据

失败报错

- 数据重复报错 `ortoise.exceptions.IntegrityError`
- 数据类型报错 `ValueError`
- 数据库操作错误 `OperationalError`, 例如连接错误、超时等

```python
## main.py

# create() 方法
# 返回数据对象
# 数据重复报错 ortoise.exceptions.IntegrityError
# 数据类型报错 ValueError
# 数据库操作错误 OperationalError, 例如连接错误、超时等
from tortoise.exceptions import IntegrityError, OperationalError

async def create_data():
    try:
        new_data = await Proverbs.create(proverb='测试数据1', author='孔子', description='描述')
        print(new_data.id, new_data.proverb, new_data.author, new_data.description)
    except ValueError as e:
        print(e)
    except IntegrityError as e:
        print(e)
    except OperationalError as e:
        print(e)


run_async(create_data())
```



### save

成功返回数据对象，通过 `.` 获取数据

失败报错

- 数据重复报错 `ortoise.exceptions.IntegrityError`
- 数据类型报错 `ValueError`
- 数据库操作错误 `OperationalError`, 例如连接错误、超时等

``` python
## main.py

# .save()
# 返回数据对象
# 数据重复报错 ortoise.exceptions.IntegrityError
# 数据类型报错 ValueError
# 数据库操作错误 OperationalError, 例如连接错误、超时等
# 新增数据
from tortoise.exceptions import IntegrityError, OperationalError

async def create_data():
    try:
        new_data = Proverbs(proverb='知之为，知为不知', author='孔子', description='描述')
        await new_data.save()
        print(new_data.id, new_data.proverb, new_data.author, new_data.description)
    except ValueError as e:
        print(e)
    except IntegrityError as e:
        print(e)
    except OperationalError as e:
        print(e)


run_async(create_data())
```



## 多条数据新增

### bulk_create

成功返回返回数据对象列表 [<模型>, <模型>]

失败报错

- 数据重复报错 `ortoise.exceptions.IntegrityError`
- 数据类型报错 `ValueError`
- 数据库操作错误 `OperationalError`, 例如连接错误、超时等

```python
# 批量新增数据
# 返回数据对象列表 [<模型>, <模型>]
# 数据重复报错 ortoise.exceptions.IntegrityError
# 数据类型报错 ValueError
# 数据库操作错误 OperationalError, 例如连接错误、超时等
from tortoise.exceptions import IntegrityError, OperationalError


async def create_many_data():
  
    new_datas = [
        {'proverb': '测试数据6', 'author': '作者6', 'description': '描述6'},
        {'proverb': '测试数据7', 'author': '作者7', 'description': '描述7'},
    ]
    
    # 构造数据为 -> [Proverbs(proverb='测试数据1', author='孔子', description='描述'),...]
    new_data_model = [Proverbs(**data) for data in new_datas]
    
    
    try:
        back_data = await Proverbs.bulk_create(new_data_model)
        
        print_data = [(i.id, i.proverb, i.author, i.description) for i in back_data]
        
        print(print_data)
        # [(None, '测试数据6', '作者6', '描述6'), (None, '测试数据7', '作者7', '描述7')]
        # 多条插入 id 返回值为 None
        
        
    except ValueError as e:
        print(e)
    except IntegrityError as e:
        print(e)
        # (1062, "Duplicate entry '测试数据6' for key 'proverbs.proverb'")
        # 会将哪个数据有错误返回出来， 这个错误就是 重复
    except OperationalError as e:
        print(e)

run_async(create_many_data())
```



